baseURL = "https://www.retrix.me/"
languageCode = "en-us"
title = "RetriX"
theme = "Material"

[Params]
    demoVideoLink = "https://www.youtube.com/embed/1mzS54HhcEM"
    downloadLink = "https://github.com/Aftnet/LibretroRT/releases/download/v1.9.2/RetriX.UWP_1.9.2.0_x86_x64_arm.appxbundle"
    donateLink = "https://www.patreon.com/aftnet"
    githubPage = "https://github.com/Aftnet/LibretroRT"
    guidePage = "https://github.com/Aftnet/LibretroRT/wiki"
    twitterPage = "https://twitter.com/aftnet"
    discordPage = "https://discord.gg/AJM9ahm"
    authorName = "Alberto Fustinoni"
    authorLink = "https://www.aftnet.net"
    analyticsID = "UA-22182855-2"
