baseURL = "https://www.retrix.me/"
languageCode = "en-us"
title = "RetriX"
theme = "Material"

[Params]
    downloadLink = "https://github.com/Aftnet/LibretroRT/releases/download/NGP_WSwan/RetriX.UWP_1.4.10.0_x86_x64_arm.appxbundle"
    donateLink = "https://www.gofundme.com/retrix"
    githubPage = "https://github.com/aftnet/LibretroRT"
    twitterPage = "https://twitter.com/aftnet"